// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Xr8_kVf3MQJYfHT9C3Y2Z-W-ZVFbvZg',
    appId: '1:1062614738173:android:4befe172dfcc0f94164a94',
    messagingSenderId: '1062614738173',
    projectId: 'traces-1a3f2',
    databaseURL: 'https://traces-1a3f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'traces-1a3f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPcsNPZ1lMB-43cW7e07r8p5YU-OdU8ks',
    appId: '1:1062614738173:ios:487a4e37b83c6ac0164a94',
    messagingSenderId: '1062614738173',
    projectId: 'traces-1a3f2',
    databaseURL: 'https://traces-1a3f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'traces-1a3f2.firebasestorage.app',
    iosClientId: '1062614738173-o7rlirqj2rbncs4hsenjc7g2e0hfptc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverApp',
  );

}